jadcoffer:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: jadcoffer
    username: root
    password: !
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    bucket-name: fengzi3364
    access-key-id:  
    access-key-secret:  
  redis:
    host: 127.0.0.1
    port: 6379
    password: !
    timeout: 5000


    # Apifox令牌: APS-7St8VIvKqLnnQINBAaCHjsFaAxZfNIYv
