server:
  port: 18080

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${jadcoffer.datasource.driver-class-name}
      url: jdbc:mysql://${jadcoffer.datasource.host}:${jadcoffer.datasource.port}/${jadcoffer.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${jadcoffer.datasource.username}
      password: ${jadcoffer.datasource.password}
  redis:
    host: 127.0.0.1
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,templates/**


springdoc:
  api-docs:
    enabled: true

mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      waverly:
        jadcoffer:
          mapper: debug
          service: info
          controller: info

jadcoffer:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: waverly
    # 设置jwt过期时间
    user-ttl: 720000000
    # 设置前端传递过来的令牌名称
    user-token-name: authentication
  alioss:
    endpoint: ${jadcoffer.alioss.endpoint}
    access-key-id: ${jadcoffer.alioss.access-key-id}
    access-key-secret: ${jadcoffer.alioss.access-key-secret}
    bucket-name: ${jadcoffer.alioss.bucket-name}
